# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SignInWithAppleWithFirebaesAuthSample' do
  use_frameworks!
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
end

target 'UserAccount' do
  use_frameworks!
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
end
